inherit_gem:
  bixby: bixby_default.yml

AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true
  Exclude:
    - 'spec/internal_test_hyrax/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

Metrics/BlockLength:
  Exclude:
    - 'hyrax-doi.gemspec'
    - 'lib/hyrax/doi/spec/shared_specs/*'
    - 'spec/**/*'

Layout/LineLength:
  Exclude:
    - 'spec/support/datacite_api_stubs.rb'

Style/RedundantSelf:
  Exclude:
    - 'app/services/hyrax/doi/datacite_registrar.rb'
