inherit_gem:
  bixby: bixby_default.yml

AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true
  Exclude:
    - 'spec/internal_test_hyrax/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

Metrics/BlockLength:
  Exclude:
    - 'lib/hyrax/doi/spec/shared_specs/*'
    - 'spec/**/*'
